# Generated by Django 2.2.6 on 2019-11-23 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('eletrodomesticos', 'ELETRODOMÉSTICOS'), ('roupas', 'ROUPAS'), ('moveis', 'MÓVEIS'), ('brinquedos', 'BRINQUEDOS'), ('jogos', 'JOGOS'), ('decoracao', 'DECORAÇÃO'), ('outros', 'OUTROS')], max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('color', models.CharField(choices=[('azul', 'AZUL'), ('vermelho', 'VERMELHO'), ('verde', 'VERDE'), ('prata', 'PRATEADO'), ('preto', 'PRETO')], max_length=8)),
                ('size', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('sold_off', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja_api.Categoria', verbose_name='produtos')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField()),
                ('freight', models.FloatField()),
                ('total_value', models.FloatField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='compras')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_buy', models.IntegerField()),
                ('value_itens', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja_api.Item', verbose_name='compra')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja_api.Purchase', verbose_name='itens')),
            ],
        ),
        migrations.CreateModel(
            name='InformacoesUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('telephone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=11)),
                ('cep', models.CharField(max_length=8)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='informacoes')),
            ],
        ),
        migrations.CreateModel(
            name='CarteiraDigital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_account', models.IntegerField()),
                ('value', models.FloatField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='carteira')),
            ],
        ),
    ]
