# Generated by Django 2.2.6 on 2019-11-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_api', '0002_auto_20191124_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sold_off',
            field=models.BooleanField(default=False),
        ),
    ]
