# Generated by Django 2.2.6 on 2019-11-26 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja_api', '0003_auto_20191126_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteiradigital',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='carteira'),
        ),
        migrations.AlterField(
            model_name='informacoesusuario',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='informacoes'),
        ),
    ]
