# Generated by Django 2.2.6 on 2019-11-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja_api', '0004_auto_20191126_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacoesusuario',
            name='email',
        ),
    ]
