# Generated by Django 2.2.7 on 2019-12-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_api', '0005_remove_informacoesusuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(max_length=25),
        ),
    ]
