# Generated by Django 2.2.7 on 2019-12-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_api', '0006_auto_20191204_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='description',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
