# Generated by Django 2.2.7 on 2019-12-06 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja_api', '0007_categoria_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoesusuario',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
