# Generated by Django 2.2.7 on 2019-12-06 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja_api', '0008_auto_20191206_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempurchase',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja_api.Item', verbose_name='itens'),
        ),
        migrations.AlterField(
            model_name='itempurchase',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja_api.Purchase', verbose_name='compra'),
        ),
    ]
